### ISSUE TITLE
MultiBranch Plugin stopped working with latest Jenkins.

### ISSUE THREAD

**Issue by timomayer** [mjdetullio/multi-branch-project-plugin#113]
I always get this error with latest jenkins:
Setting origin to https://git.virtual-identity.com/scm/ui/ui-privatkunden-frontend-framework.git
Fetching origin...
FATAL: Could not initialize class org.eclipse.jgit.transport.Transport
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.transport.Transport

The bug was reportet here too:
https://groups.google.com/forum/#!topic/jenkinsci-users/Q5ONa5eZcnA

Can you please look into that issue? Thanks a lot.

**Comment by maxcom** [comment]
Same problem :-(

**Comment by mjdetullio** [comment]
latest Jenkins being 1.634?  which Git Plugin version?

**Comment by timomayer** [comment]
Jenkins ver. 1.633 in my case but it did not work with 1.634 either. i am on ubuntu 14.04

**Comment by gorbeia** [comment]
This seems to be a duplicate of #107. As explained there it seems to be corrected with version 1.634 of jenkins.

**Comment by mariotux** [comment]
Jenkins 1.634
GIT Plugin: 2.4.0
GIT client plugin: 1.19.0

With these versions, it work well. May be other plugin with a conflict.
